name: author-search-engine
on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
      - 
        name: Build and push
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/author-search-engine
      -
        name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
